Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"
  
    config.vm.box_check_update = true
  
   
    config.vm.network "forwarded_port", guest: 80, host: 8000
   
    config.vm.provider "virtualbox" do |vb|
    end
   
    config.vm.provision "shell", path: "prov_scr.sh"
  end
  