Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.box_check_update = true

 
  config.vm.network "forwarded_port", guest: 8090, host: 8080
  config.vm.network "forwarded_port", guest: 3306, host: 3306
 
  config.vm.provider "virtualbox" do |vb|
  
    vb.memory = "3024"
  end
 
  config.vm.provision "shell", path: "ConfluenceSetup.sh"
end
